version: "3.4"
services:
  redis:
    image: redis:7.0
    container_name: 'redis-master'
    ports:
      - "6379:6379"
    shm_size: 512MB
    # 'redis-server' refers to who persists data;
    # --save every n seconds if at least 1 write
    command: ["redis-server", "--save", "1200", "1", "--loglevel", "warning"]
    volumes:
      - redis-data:/data
    networks:
      - redis-network
    restart: unless-stopped

  rabbitmq.hw:
    image: masstransit/rabbitmq:3
    container_name: 'rabbit_mq_hw'
    # name for node where data is stored
    hostname: rabbit_node_hw
    volumes:
      - rabbitmq-var:/var/lib/rabbitmq
      - rabbitmq-etc:/etc/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - redis-network
    restart: unless-stopped

# these refer to volumes created using 'docker volume create'
volumes:
  redis-data:
    external: true
    name: local_redis_storage
  rabbitmq-var:
    external: true
    name: local_rabbitmq_var
  rabbitmq-etc:
    external: true
    name: local_rabbitmq_etc
networks:
  redis-network:
    driver: bridge